name: matcha

services:
  nginx:
    image: nginx:latest
    container_name: matcha-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      client:
        condition: service_completed_successfully
      server:
        condition: service_healthy
    networks:
      - matcha-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: matcha-client
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/build:/app/build
    networks:
      - matcha-network
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost/api}
      - REACT_APP_FRONTEND_URL=${REACT_APP_FRONTEND_URL:-http://localhost}
    command: npm run build

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: matcha-server
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - matcha-network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-matcha}
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
      - DB_PORT=${DB_PORT:-5432}
      - SERVER_PORT=${SERVER_PORT:-8000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your_jwt_secret}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN:-60}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN:-7}
    depends_on:
      database:
        condition: service_healthy
    command: npm run start
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://server:8000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  database:
    image: postgres:17
    container_name: matcha-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-matcha}
      - TZ=UTC
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matcha-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  matcha-network:
    driver: bridge

volumes:
  postgres_data:
