###

@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzZXJ2ZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzk4NzYzNDksImV4cCI6MTc0MDQ4MTE0OX0.Hs7uVxskV8pvD2trnDW7BxvrZGWnHWKCYGjUn3srVYw
@authToken_test=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTczOTg5MzA0MSwiZXhwIjoxNzQwNDk3ODQxfQ.wjjFG6fRyvC7pRUHxOGPYqIIzO6o4WbQgJiKIezfKuk

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "server",
    "password": "password"
}

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "password"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "firstName": "Server",
    "lastName": "Tester",
    "username": "server",
    "email": "server@example.com",
    "password": "password"
}

### Add like

POST http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

### Remove like

DELETE http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

### Add like to make a match

POST http://localhost:8000/users/2/likes
Cookie: authToken={{authToken_test}}

### Remove match

DELETE http://localhost:8000/users/16/matches
Cookie: authToken={{authToken}}

### Add view

POST http://localhost:8000/users/16/views
Cookie: authToken={{authToken}}
