###

@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImVtYWlsIjoic2VydmVyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM4ODM3NTUxLCJleHAiOjE3Mzk0NDIzNTF9.u7om6OFPydEu5BmA3Rp9dyFFNvtTtZqGwf5uXJlaNk4

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "server",
    "password": "password"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "firstName": "Server",
    "lastName": "Tester",
    "username": "server",
    "email": "server@example.com",
    "password": "password"
}

### Add like

POST http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

### Remove like

DELETE http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

