@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImVtYWlsIjoic2VydmVyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM4NTg5Njg5LCJleHAiOjE3MzkxOTQ0ODl9.2z3tzoW-EW22ynJJRFgDtiIBcuCSAV-fCS_NQQDdIz4
###

GET http://localhost:8000/users
Cookie: authToken={{authToken}}

###
### Likes routes
###

### Check if user likes another user

GET http://localhost:8000/users/16/liked
Cookie: authToken={{authToken}}

### Get all likes

GET http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

### Add like

POST http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

### Remove like

DELETE http://localhost:8000/users/16/likes
Cookie: authToken={{authToken}}

###
### Matches routes
###

### Get all matches

GET http://localhost:8000/users/1/matches
Cookie: authToken={{authToken}}

### Tags routes

GET http://localhost:8000/users/1/tags
Cookie: authToken={{authToken}}

###

POST http://localhost:8000/users/1/tags
Cookie: authToken={{authToken}}
Content-Type: application/json

{
    "tagId": "10"
}

###

DELETE http://localhost:8000/users/1/tags
Cookie: authToken={{authToken}}
Content-Type: application/json

{
    "tagId": "10"
}

###