###

@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTczNzgyNjE5OCwiZXhwIjoxNzM4NDMwOTk4fQ.umFi9trAcvmZRucngS0GvPb3EoCK39ujvh7Ir4CNzXU

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "password"
}

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "server",
    "password": "password"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "firstName": "testname",
    "lastName": "tester", 
    "username": "test",
    "email": "test@example.com",
    "password": "password"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "firstName": "Server",
    "lastName": "Tester",
    "username": "server",
    "email": "server@example.com",
    "password": "password"
}

### Logout

POST http://localhost:8000/auth/logout
Cookie: authToken={{authToken}}

### Check
GET http://localhost:8000/auth/check
Cookie: authToken={{authToken}}
