name: matcha

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-matcha}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-matcha}
      POSTGRES_DB: ${POSTGRES_DB:-matcha}
      TZ: "UTC"
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
