
GET http://localhost:8000

###

GET http://localhost:8000/users/19

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "firstName": "666",
    "lastName": "661", 
    "username": "66",
    "email": "t666rample.co",
    "password": "123"
}

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "66",
    "password": "123"
}