### Auth token

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTczNjM1Mzc1MSwiZXhwIjoxNzM2OTU4NTUxfQ.dcGHxjzUraoeiJ8gfUZW0vDLZ61xCzLVRd60-WxjdZQ
### 

GET http://localhost:8000/users
Cookie: authToken={{authToken}}

### Search by age

GET http://localhost:8000/users/search?maxAge=30&minAge=20
Cookie: authToken={{authToken}}

### Search by fame rating

GET http://localhost:8000/users/search?maxFameRating=0&&minFameRating=10
Cookie: authToken={{authToken}}

### Search by distance

GET http://localhost:8000/users/search?distance=1000&latitude=42&longitude=2
Cookie: authToken={{authToken}}

### Search by tags

GET http://localhost:8000/users/search?tags=science
Cookie: authToken={{authToken}}

### Search by gender

GET http://localhost:8000/users/search?gender=other
Cookie: authToken={{authToken}}

### Search by preferences

GET http://localhost:8000/users/search?sexualPreferences=male
Cookie: authToken={{authToken}}

### Search by gender and preferences

GET http://localhost:8000/users/search?sexualPreferences=other&gender=male
Cookie: authToken={{authToken}}

### Search with all filters

GET http://localhost:8000/users/search
Cookie: authToken={{authToken}}
