### Auth token

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzM1OTE0ODk2LCJleHAiOjE3MzY1MTk2OTZ9.5Dpq5P4Mflg5YKacSIQMyn7n5NoMOpudNNFPDLkmL6U

### 

GET http://localhost:8000/users
Cookie: authToken={{authToken}}

###