###

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzM0OTc0MDA3LCJleHAiOjE3MzU1Nzg4MDd9.pkyntmH_mCFvPzDFMLniXGPXdc67IdvOAi_jzjFAO6M

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "password"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "firstName": "testname",
    "lastName": "tester", 
    "username": "test",
    "email": "test@example.com",
    "password": "password"

}

### Logout

POST http://localhost:8000/auth/logout
Cookie: authToken={{authToken}}

###