### Auth token

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzM2NDI2NTM2LCJleHAiOjE3MzcwMzEzMzZ9.tTxUZSWLIqCwpY_DSFovvqFKh2ZWSshz4lqpcLAvKS0
### 

GET http://localhost:8000/users
Cookie: authToken={{authToken}}

### Search by age

GET http://localhost:8000/users/search?ageMax=30&ageMin=20
Cookie: authToken={{authToken}}

###

GET http://localhost:8000/users/search?ageMax=30&ageMin=50
Cookie: authToken={{authToken}}

### Search by fame rating

GET http://localhost:8000/users/search?maxFameRating=10&&minFameRating=10
Cookie: authToken={{authToken}}

### 

GET http://localhost:8000/users/search?maxFameRating=0&&minFameRating=20
Cookie: authToken={{authToken}}

### Search by distance

GET http://localhost:8000/users/search?distance=1000&latitude=42&longitude=2
Cookie: authToken={{authToken}}

### Search by tags

GET http://localhost:8000/users/search?tags=science
Cookie: authToken={{authToken}}

### Search by gender

GET http://localhost:8000/users/search?gender=other
Cookie: authToken={{authToken}}

### Search by preferences

GET http://localhost:8000/users/search?sexualPreferences=male
Cookie: authToken={{authToken}}

### Search by gender and preferences

GET http://localhost:8000/users/search?sexualPreferences=male&gender=male
Cookie: authToken={{authToken}}

### Search with all filters

GET http://localhost:8000/users/search/?ageMax=60&ageMin=20&maxFameRating=150&minFameRating=0&distance=1000&latitude=42&longitude=2&tags=food&gender=male&sexualPreferences=female
Cookie: authToken={{authToken}}

### Search without filters

GET http://localhost:8000/users/search
Cookie: authToken={{authToken}}
